import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";

const connectionString = process.env.DATABASE_URL;
const adapter = new PrismaPg({ connectionString });

const prisma = new PrismaClient({ adapter });

const meals = [
  
  //High risk Meals
  

  // BREAKFAST
  {
    name: "Plain Yogurt with Almonds",
    description: "A simple high protein breakfast with healthy fats",
    whyItHelps: "High protein yogurt stabilizes blood sugar. Almonds provide healthy fats that reduce insulin resistance in PCOS",
    ingredients: ["150g plain yogurt", "10 almonds"],
    recipe: ["Spoon yogurt into a bowl and top with almonds.", "Serve chilled."],
    mealType: "BREAKFAST",
    riskCategory: "HIGH_RISK",
    calories: 220,
    carbs: 12,
    prepTime: "5 mins",
    isVeg: true,
  },
  {
    name: "Egg Spinach Scramble with Avocado",
    description: "Protein rich scrambled eggs with healthy fats",
    whyItHelps: "Eggs provide complete protein. Avocado healthy fats reduce androgen levels in PCOS",
    ingredients: ["2 eggs", "100g spinach", "half avocado", "1 tsp oil", "salt", "pepper"],
    recipe: ["Beat eggs with salt and pepper until combined.", "Heat oil in a pan over medium heat and wilt the spinach for 1–2 minutes.", "Pour in the eggs and cook gently, folding until just set.", "Slice the avocado and serve alongside."],
    mealType: "BREAKFAST",
    riskCategory: "HIGH_RISK",
    calories: 380,
    carbs: 8,
    prepTime: "10 mins",
    isVeg: true,
  },
  {
    name: "Grilled Paneer with Celery",
    description: "Simple grilled paneer with fresh celery sticks",
    whyItHelps: "High protein breakfast reduces morning insulin spikes. Celery is anti-inflammatory",
    ingredients: ["150g paneer", "3 stalks celery", "1 tsp oil", "salt", "pepper"],
    recipe: ["Cut paneer into even slices and season with salt and pepper.", "Brush a pan with oil and grill over medium-high heat for 3 minutes each side until golden.", "Serve with fresh celery stalks on the side."],
    mealType: "BREAKFAST",
    riskCategory: "HIGH_RISK",
    calories: 280,
    carbs: 6,
    prepTime: "15 mins",
    isVeg: true,
  },
  {
    name: "Avocado with Boiled Egg",
    description: "Creamy avocado topped with sliced boiled eggs",
    whyItHelps: "Avocado monounsaturated fats improve insulin sensitivity. Eggs provide choline for hormonal balance",
    ingredients: ["1 avocado", "2 boiled eggs", "salt", "pepper", "lemon"],
    recipe: ["Halve and pit the avocado.", "Peel and slice the boiled eggs.", "Arrange egg slices over the avocado halves, season with salt and pepper, and finish with a squeeze of lemon."],
    mealType: "BREAKFAST",
    riskCategory: "HIGH_RISK",
    calories: 350,
    carbs: 8,
    prepTime: "10 mins",
    isVeg: true,
  },
  {
    name: "Yogurt with Chia Seeds and Cucumber",
    description: "Probiotic yogurt with omega-3 rich chia seeds",
    whyItHelps: "Chia seeds omega-3 and fiber reduce insulin resistance. Yogurt probiotics improve gut-hormone axis",
    ingredients: ["150g plain yogurt", "5g chia seeds", "half cucumber sliced"],
    recipe: ["Stir chia seeds into the yogurt and let sit for 5 minutes to thicken.", "Slice the cucumber and serve alongside."],
    mealType: "BREAKFAST",
    riskCategory: "HIGH_RISK",
    calories: 200,
    carbs: 14,
    prepTime: "8 mins",
    isVeg: true,
  },
  {
    name: "Paneer with Cucumber",
    description: "Fresh paneer cubes with cucumber slices",
    whyItHelps: "High protein low carb breakfast prevents morning cortisol spike common in PCOS",
    ingredients: ["150g paneer", "1 cucumber sliced", "salt", "black pepper", "lemon"],
    recipe: ["Cut paneer into bite-sized cubes and arrange on a plate.", "Slice the cucumber and place alongside.", "Season with salt, black pepper, and a squeeze of lemon before serving."],
    mealType: "BREAKFAST",
    riskCategory: "HIGH_RISK",
    calories: 260,
    carbs: 6,
    prepTime: "5 mins",
    isVeg: true,
  },
  {
    name: "Yogurt with Chia Seeds",
    description: "Simple chia seed yogurt bowl",
    whyItHelps: "Chia seeds fiber slows glucose absorption. Yogurt protein keeps hunger at bay",
    ingredients: ["150g plain yogurt", "5g chia seeds"],
    recipe: ["Stir chia seeds into the yogurt and allow to sit for 5 minutes before serving."],
    mealType: "BREAKFAST",
    riskCategory: "HIGH_RISK",
    calories: 180,
    carbs: 12,
    prepTime: "5 mins",
    isVeg: true,
  },

  // LUNCH
  {
    name: "Tuna Spinach Salad with Mustard Oil",
    description: "Light and nutritious salad packed with omega-3",
    whyItHelps: "Tuna omega-3s reduce PCOS inflammation. Spinach provides iron and magnesium",
    ingredients: ["150g tuna", "100g spinach", "1 tbsp mustard oil", "salt", "pepper"],
    recipe: ["Drain the tuna thoroughly and break into flakes.", "Toss with fresh spinach and drizzle with mustard oil.", "Season with salt and pepper and serve immediately."],
    mealType: "LUNCH",
    riskCategory: "HIGH_RISK",
    calories: 320,
    carbs: 8,
    prepTime: "10 mins",
    isVeg: false,
  },
  {
    name: "Paneer Salad with Onion and Green Chili",
    description: "Fresh paneer salad with Nepali spices",
    whyItHelps: "Paneer high protein reduces hunger. Mustard oil anti-inflammatory properties help hormonal balance",
    ingredients: ["150g paneer", "1 onion sliced", "2 green chilies", "1 tbsp mustard oil", "coriander", "salt"],
    recipe: ["Cut paneer into cubes and place in a bowl.", "Add thinly sliced onion and finely chopped green chilies.", "Drizzle with mustard oil, season with salt, and toss well.", "Garnish with fresh coriander before serving."],
    mealType: "LUNCH",
    riskCategory: "HIGH_RISK",
    calories: 340,
    carbs: 10,
    prepTime: "10 mins",
    isVeg: true,
  },
  {
    name: "Egg Salad with Mustard Oil and Spinach",
    description: "Boiled egg salad on a bed of fresh spinach",
    whyItHelps: "Eggs and spinach provide iron, B12 and protein essential for hormonal health",
    ingredients: ["3 boiled eggs", "100g spinach", "1 tbsp mustard oil", "salt", "pepper", "lemon"],
    recipe: ["Peel and slice the boiled eggs.", "Dress the spinach with mustard oil, salt, and pepper.", "Arrange the egg slices over the spinach and finish with a squeeze of lemon."],
    mealType: "LUNCH",
    riskCategory: "HIGH_RISK",
    calories: 300,
    carbs: 6,
    prepTime: "15 mins",
    isVeg: true,
  },
  {
    name: "Chicken Lettuce Rolls with Mint",
    description: "Low carb chicken rolls wrapped in fresh lettuce",
    whyItHelps: "Low carb wrap with lean protein. Mint aids digestion and reduces bloating common in PCOS",
    ingredients: ["150g chicken breast", "4 lettuce leaves", "mint leaves", "garlic", "1 tbsp mustard oil", "salt"],
    recipe: ["Cook the chicken breast with garlic until done, then shred finely.", "Season with salt and a drizzle of mustard oil.", "Spoon onto lettuce leaves, top with fresh mint, roll tightly, and serve."],
    mealType: "LUNCH",
    riskCategory: "HIGH_RISK",
    calories: 310,
    carbs: 6,
    prepTime: "20 mins",
    isVeg: false,
  },
  {
    name: "Rohu Fish with Spinach",
    description: "Pan-fried rohu fish on a bed of sauteed spinach",
    whyItHelps: "Rohu omega-3 content significantly reduces PCOS inflammation markers",
    ingredients: ["200g rohu fish", "150g spinach", "1 tbsp mustard oil", "garlic", "salt"],
    recipe: ["Heat mustard oil in a pan over medium-high heat and fry the fish for 5 minutes each side until golden.", "In a separate pan, sauté garlic briefly, then add spinach and cook until just wilted.", "Plate the spinach and rest the fish on top."],
    mealType: "LUNCH",
    riskCategory: "HIGH_RISK",
    calories: 400,
    carbs: 6,
    prepTime: "20 mins",
    isVeg: false,
  },
  {
    name: "Chicken Pickle Salad",
    description: "Spiced shredded chicken with pickled vegetables",
    whyItHelps: "Lean protein with fermented vegetables supports gut health and hormone regulation",
    ingredients: ["150g chicken breast", "mixed vegetables", "1 tbsp mustard oil", "pickle spices", "salt"],
    recipe: ["Cook the chicken breast until done, then shred into thin strips.", "Combine with pickled vegetables and toss with mustard oil.", "Adjust seasoning and serve."],
    mealType: "LUNCH",
    riskCategory: "HIGH_RISK",
    calories: 320,
    carbs: 8,
    prepTime: "25 mins",
    isVeg: false,
  },
  {
    name: "Egg Spinach Salad",
    description: "Simple boiled egg and spinach salad",
    whyItHelps: "Complete protein and iron rich lunch that stabilizes blood sugar throughout the afternoon",
    ingredients: ["2 boiled eggs", "100g spinach", "1 tbsp mustard oil", "salt", "pepper"],
    recipe: ["Peel and slice the boiled eggs.", "Toss the spinach with mustard oil, salt, and pepper.", "Arrange the egg slices on top and serve."],
    mealType: "LUNCH",
    riskCategory: "HIGH_RISK",
    calories: 260,
    carbs: 5,
    prepTime: "10 mins",
    isVeg: true,
  },

  // DINNER
  {
    name: "Rohu Fish with Cauliflower Curry",
    description: "Traditional Nepali fish curry with low carb vegetables",
    whyItHelps: "Rohu omega-3s reduce PCOS inflammation. Cauliflower fiber stabilizes insulin levels",
    ingredients: ["200g rohu fish", "200g cauliflower", "1 tbsp mustard oil", "turmeric", "cumin", "salt"],
    recipe: ["Heat mustard oil in a pan and fry the fish for 5 minutes each side, then set aside.", "In the same pan, stir-fry cauliflower florets with turmeric, cumin, and salt until tender.", "Return the fish to the pan, combine gently, and serve hot."],
    mealType: "DINNER",
    riskCategory: "HIGH_RISK",
    calories: 450,
    carbs: 15,
    prepTime: "25 mins",
    isVeg: false,
  },
  {
    name: "Chicken Choila with Zucchini",
    description: "Nepali style spiced chicken with low carb zucchini",
    whyItHelps: "Lean chicken protein supports muscle mass. Zucchini low carb keeps insulin stable",
    ingredients: ["200g chicken breast", "150g zucchini", "1 tbsp mustard oil", "garlic", "ginger", "spices"],
    recipe: ["Boil the chicken until fully cooked, then shred and toss with garlic, ginger, and spices.", "Stir-fry the zucchini separately until just tender.", "Combine both with mustard oil and serve warm."],
    mealType: "DINNER",
    riskCategory: "HIGH_RISK",
    calories: 420,
    carbs: 12,
    prepTime: "30 mins",
    isVeg: false,
  },
  {
    name: "Grilled Rohu Fish with Bitter Gourd",
    description: "Grilled fish paired with insulin-lowering bitter gourd",
    whyItHelps: "Bitter gourd has proven insulin-lowering properties. Combined with omega-3 fish reduces PCOS symptoms",
    ingredients: ["200g rohu fish", "150g bitter gourd", "1 tbsp mustard oil", "turmeric", "salt"],
    recipe: ["Marinate the fish with turmeric and salt for 10 minutes.", "Grill for 7 minutes each side until cooked through.", "Meanwhile, sauté bitter gourd in mustard oil over medium heat until softened.", "Plate together and serve."],
    mealType: "DINNER",
    riskCategory: "HIGH_RISK",
    calories: 380,
    carbs: 10,
    prepTime: "25 mins",
    isVeg: false,
  },
  {
    name: "Tofu Spinach Curry with Mustard Oil",
    description: "Creamy tofu and spinach curry cooked in mustard oil",
    whyItHelps: "Tofu phytoestrogens help balance hormones. Spinach magnesium reduces cortisol in PCOS",
    ingredients: ["200g tofu", "200g spinach", "1 tbsp mustard oil", "garlic", "turmeric", "salt"],
    recipe: ["Cut tofu into cubes and pan-fry until golden on all sides, then set aside.", "In the same pan, heat mustard oil and sauté garlic with turmeric.", "Add spinach and cook until wilted, then fold in the tofu.", "Season with salt and serve hot."],
    mealType: "DINNER",
    riskCategory: "HIGH_RISK",
    calories: 380,
    carbs: 12,
    prepTime: "20 mins",
    isVeg: true,
  },
  {
    name: "Lean Mutton with Cauliflower",
    description: "Slow cooked lean mutton with steamed cauliflower",
    whyItHelps: "Lean mutton iron and zinc support thyroid function often impaired in PCOS",
    ingredients: ["150g lean mutton", "200g cauliflower", "1 tbsp mustard oil", "ginger", "garlic", "spices"],
    recipe: ["Cook the mutton with ginger, garlic, and spices over low heat until tender, about 30 minutes.", "Steam the cauliflower separately until just cooked.", "Combine in the pan for a final 5 minutes, finish with mustard oil, and serve."],
    mealType: "DINNER",
    riskCategory: "HIGH_RISK",
    calories: 460,
    carbs: 14,
    prepTime: "40 mins",
    isVeg: false,
  },
  {
    name: "Rohu Fish with Palak Spinach",
    description: "Classic fish and spinach curry with Nepali spices",
    whyItHelps: "Combined omega-3 and iron from fish and spinach directly targets PCOS hormonal imbalance",
    ingredients: ["200g rohu fish", "200g palak spinach", "1 tbsp mustard oil", "garlic", "turmeric", "salt"],
    recipe: ["Fry the fish in mustard oil for 5 minutes each side, then set aside.", "Blend the spinach into a smooth purée and cook with garlic and turmeric for 5 minutes.", "Return the fish and simmer for a further 10 minutes before serving."],
    mealType: "DINNER",
    riskCategory: "HIGH_RISK",
    calories: 430,
    carbs: 10,
    prepTime: "30 mins",
    isVeg: false,
  },
  {
    name: "Chicken Cauliflower Curry",
    description: "Light chicken curry with cauliflower instead of potatoes",
    whyItHelps: "Cauliflower replaces high carb potato. Chicken protein maintains muscle and metabolism in PCOS",
    ingredients: ["200g chicken breast", "200g cauliflower", "1 tbsp mustard oil", "onion", "garlic", "spices"],
    recipe: ["Sauté diced onion and garlic in mustard oil until golden.", "Add the chicken and cook through, stirring occasionally.", "Add cauliflower florets and spices with a splash of water and simmer for 15 minutes until tender.", "Serve hot."],
    mealType: "DINNER",
    riskCategory: "HIGH_RISK",
    calories: 410,
    carbs: 14,
    prepTime: "35 mins",
    isVeg: false,
  },

  // SNACK
  {
    name: "Cucumber Slices",
    description: "Simple refreshing low carb snack",
    whyItHelps: "Low carb high water content keeps you full without spiking blood sugar",
    ingredients: ["1 medium cucumber", "pinch of salt"],
    recipe: ["Slice the cucumber into thin rounds, sprinkle with salt, and serve chilled."],
    mealType: "SNACK",
    riskCategory: "HIGH_RISK",
    calories: 50,
    carbs: 5,
    prepTime: "5 mins",
    isVeg: true,
  },
  {
    name: "Almonds",
    description: "Simple handful of raw almonds",
    whyItHelps: "Almonds reduce fasting insulin and lower androgen levels in PCOS women",
    ingredients: ["15 almonds"],
    recipe: ["Serve as is."],
    mealType: "SNACK",
    riskCategory: "HIGH_RISK",
    calories: 100,
    carbs: 4,
    prepTime: "1 min",
    isVeg: true,
  },
  {
    name: "Roasted Chickpeas",
    description: "Crunchy spiced roasted chickpeas",
    whyItHelps: "Plant protein and fiber prevent blood sugar spikes between meals",
    ingredients: ["20g chickpeas", "1 tsp oil", "salt", "cumin"],
    recipe: ["Toss the chickpeas with oil, salt, and cumin until evenly coated.", "Roast in a dry pan over medium heat for 10 minutes, stirring frequently, until crisp.", "Cool slightly before serving."],
    mealType: "SNACK",
    riskCategory: "HIGH_RISK",
    calories: 80,
    carbs: 10,
    prepTime: "12 mins",
    isVeg: true,
  },
  {
    name: "Low Carb Pickle",
    description: "Homemade fermented vegetable pickle",
    whyItHelps: "Fermented foods improve gut health and reduce PCOS-related inflammation",
    ingredients: ["cucumber", "green chili", "vinegar", "salt", "mustard seeds"],
    recipe: ["Slice the cucumber and green chili into thin pieces.", "Combine with vinegar, salt, and mustard seeds in a bowl.", "Mix well and allow to rest for at least 30 minutes before serving."],
    mealType: "SNACK",
    riskCategory: "HIGH_RISK",
    calories: 40,
    carbs: 4,
    prepTime: "35 mins",
    isVeg: true,
  },
  {
    name: "Spinach Stir-fry",
    description: "Quick garlic spinach stir-fry",
    whyItHelps: "Iron-rich spinach snack supports energy levels reduced by PCOS hormonal imbalance",
    ingredients: ["100g spinach", "1 tsp oil", "garlic", "salt"],
    recipe: ["Heat oil in a pan over medium heat and add sliced garlic.", "Once fragrant, add the spinach and stir-fry for 2–3 minutes until just wilted.", "Season with salt and serve immediately."],
    mealType: "SNACK",
    riskCategory: "HIGH_RISK",
    calories: 60,
    carbs: 4,
    prepTime: "5 mins",
    isVeg: true,
  },

  // ═══════════════════════════
  // LOW RISK MEALS
  // ═══════════════════════════

  // BREAKFAST
  {
    name: "Yogurt with Local Berries and Almonds",
    description: "Probiotic yogurt with antioxidant rich berries",
    whyItHelps: "Berries antioxidants reduce PCOS oxidative stress. Yogurt protein stabilizes morning blood sugar",
    ingredients: ["150g plain yogurt", "50g local berries", "10 almonds"],
    recipe: ["Spoon yogurt into a bowl, scatter berries on top, and finish with almonds.", "Serve fresh."],
    mealType: "BREAKFAST",
    riskCategory: "LOW_RISK",
    calories: 280,
    carbs: 28,
    prepTime: "5 mins",
    isVeg: true,
  },
  {
    name: "Egg Spinach Scramble with Avocado",
    description: "Protein rich scrambled eggs with healthy fats",
    whyItHelps: "Complete protein and healthy fats provide sustained energy without blood sugar spikes",
    ingredients: ["2 eggs", "100g spinach", "half avocado", "1 tsp oil", "salt"],
    recipe: ["Beat the eggs with a pinch of salt.", "Heat oil in a pan, wilt the spinach, then pour in the eggs and scramble gently until just set.", "Slice the avocado and serve on the side."],
    mealType: "BREAKFAST",
    riskCategory: "LOW_RISK",
    calories: 380,
    carbs: 10,
    prepTime: "10 mins",
    isVeg: true,
  },
  {
    name: "Paneer with Cucumber and Chia Seeds",
    description: "Protein packed paneer with hydrating cucumber",
    whyItHelps: "Chia seeds add omega-3 to this protein rich breakfast. Supports hormonal balance",
    ingredients: ["150g paneer", "1 cucumber", "5g chia seeds", "salt", "lemon"],
    recipe: ["Cut paneer into cubes and slice the cucumber.", "Arrange on a plate, scatter chia seeds over, and finish with a squeeze of lemon and a pinch of salt."],
    mealType: "BREAKFAST",
    riskCategory: "LOW_RISK",
    calories: 300,
    carbs: 14,
    prepTime: "8 mins",
    isVeg: true,
  },
  {
    name: "Spinach Yogurt Berry Smoothie",
    description: "Nutrient dense green smoothie with berries",
    whyItHelps: "Combines iron from spinach, probiotics from yogurt and antioxidants from berries for PCOS support",
    ingredients: ["100g spinach", "150g yogurt", "50g berries", "5g chia seeds"],
    recipe: ["Blend the spinach and yogurt until smooth.", "Add the berries and blend again until fully combined.", "Pour into a glass, stir in the chia seeds, and serve immediately."],
    mealType: "BREAKFAST",
    riskCategory: "LOW_RISK",
    calories: 240,
    carbs: 26,
    prepTime: "5 mins",
    isVeg: true,
  },
  {
    name: "Avocado Baked Egg",
    description: "Egg baked inside avocado halves",
    whyItHelps: "Unique combination of healthy fats and complete protein. Reduces androgen levels naturally",
    ingredients: ["1 avocado", "2 eggs", "salt", "pepper", "chili flakes"],
    recipe: ["Halve and pit the avocado, scooping out a little extra flesh to make room for the egg.", "Crack one egg into each half and season with salt, pepper, and chili flakes.", "Bake at 200°C for 15 minutes until the whites are set.", "Serve immediately."],
    mealType: "BREAKFAST",
    riskCategory: "LOW_RISK",
    calories: 360,
    carbs: 10,
    prepTime: "20 mins",
    isVeg: true,
  },
  {
    name: "Paneer Onion Almond Plate",
    description: "Simple paneer with caramelized onion and almonds",
    whyItHelps: "Balanced protein and fat breakfast that keeps blood sugar stable for hours",
    ingredients: ["150g paneer", "1 onion", "10 almonds", "1 tsp oil", "salt"],
    recipe: ["Slice the onion and sauté in oil over medium heat until golden and softened.", "Add cubed paneer to the pan and cook for 3 minutes until lightly coloured.", "Transfer to a plate, top with almonds, and serve warm."],
    mealType: "BREAKFAST",
    riskCategory: "LOW_RISK",
    calories: 320,
    carbs: 16,
    prepTime: "15 mins",
    isVeg: true,
  },
  {
    name: "Spinach Egg Scramble with Yogurt",
    description: "Scrambled eggs with spinach served with a side of yogurt",
    whyItHelps: "Triple protein from eggs, spinach and yogurt. Supports muscle and hormone production in PCOS",
    ingredients: ["2 eggs", "100g spinach", "100g yogurt", "1 tsp oil", "salt"],
    recipe: ["Heat oil in a pan and wilt the spinach over medium heat.", "Beat the eggs with salt, pour into the pan, and scramble gently until just cooked.", "Serve with a bowl of yogurt on the side."],
    mealType: "BREAKFAST",
    riskCategory: "LOW_RISK",
    calories: 300,
    carbs: 12,
    prepTime: "10 mins",
    isVeg: true,
  },

  // LUNCH
  {
    name: "Tuna Salad with Mung Beans",
    description: "Protein packed tuna salad with lentils",
    whyItHelps: "Mung beans slow-release carbs prevent afternoon energy crashes. Tuna omega-3 reduces inflammation",
    ingredients: ["150g tuna", "50g mung beans cooked", "spinach", "1 tbsp mustard oil", "lemon"],
    recipe: ["Cook the mung beans until just tender, then drain.", "Drain and flake the tuna.", "Combine tuna, mung beans, and spinach in a bowl.", "Dress with mustard oil and a squeeze of lemon, toss well, and serve."],
    mealType: "LUNCH",
    riskCategory: "LOW_RISK",
    calories: 380,
    carbs: 28,
    prepTime: "20 mins",
    isVeg: false,
  },
  {
    name: "Chicken Spinach Paneer Curry",
    description: "Protein rich curry combining chicken and paneer",
    whyItHelps: "Double protein source from chicken and paneer. Spinach iron supports energy in PCOS",
    ingredients: ["150g chicken", "100g paneer", "150g spinach", "1 tbsp mustard oil", "spices"],
    recipe: ["Cook the chicken in mustard oil with spices until cooked through.", "Add cubed paneer and stir gently.", "Fold in the spinach and cook until wilted.", "Finish with a drizzle of mustard oil and serve."],
    mealType: "LUNCH",
    riskCategory: "LOW_RISK",
    calories: 420,
    carbs: 14,
    prepTime: "30 mins",
    isVeg: false,
  },
  {
    name: "Red Lentil Soup with Spinach",
    description: "Comforting dal with iron-rich spinach",
    whyItHelps: "Lentil fiber slows carb absorption. Spinach iron addresses PCOS-related fatigue",
    ingredients: ["100g red lentils", "150g spinach", "1 tbsp mustard oil", "garlic", "cumin", "salt"],
    recipe: ["Rinse the lentils and simmer in water until soft, about 15 minutes.", "In a separate pan, heat mustard oil and sauté garlic with cumin until fragrant.", "Add spinach to the tempering and cook briefly, then stir into the lentils.", "Season with salt and serve hot."],
    mealType: "LUNCH",
    riskCategory: "LOW_RISK",
    calories: 320,
    carbs: 38,
    prepTime: "25 mins",
    isVeg: true,
  },
  {
    name: "Egg Salad with Pickle",
    description: "Classic egg salad with fermented pickle",
    whyItHelps: "Eggs provide complete protein. Pickle fermentation supports gut health linked to PCOS hormone balance",
    ingredients: ["3 eggs", "pickle vegetables", "1 tbsp mustard oil", "salt", "pepper"],
    recipe: ["Boil and peel the eggs, then slice them.", "Combine with pickled vegetables in a bowl.", "Drizzle with mustard oil, season with salt and pepper, and toss lightly before serving."],
    mealType: "LUNCH",
    riskCategory: "LOW_RISK",
    calories: 280,
    carbs: 10,
    prepTime: "15 mins",
    isVeg: true,
  },
  {
    name: "Chickpea Lentil Spinach Bowl",
    description: "Hearty plant protein bowl with greens",
    whyItHelps: "Plant proteins and fiber stabilize blood sugar. Chickpeas magnesium reduces PCOS insulin resistance",
    ingredients: ["50g chickpeas", "50g lentils", "150g spinach", "1 tbsp mustard oil", "spices"],
    recipe: ["Cook chickpeas and lentils separately until tender, then drain.", "Sauté the spinach with spices in mustard oil until wilted.", "Combine everything in a bowl, drizzle with remaining mustard oil, and serve warm."],
    mealType: "LUNCH",
    riskCategory: "LOW_RISK",
    calories: 340,
    carbs: 40,
    prepTime: "30 mins",
    isVeg: true,
  },
  {
    name: "Rohu Fish Lettuce Wraps",
    description: "Light fish wraps in crispy lettuce leaves",
    whyItHelps: "Low carb wrap keeps insulin stable. Rohu fish omega-3 reduces PCOS inflammation",
    ingredients: ["200g rohu fish", "4 lettuce leaves", "cucumber", "mustard oil", "salt", "lemon"],
    recipe: ["Pan-fry the fish in mustard oil over medium heat until cooked through and flaky.", "Break into pieces and season with salt.", "Place fish into lettuce leaves, add cucumber slices, squeeze lemon over the top, and wrap to serve."],
    mealType: "LUNCH",
    riskCategory: "LOW_RISK",
    calories: 320,
    carbs: 8,
    prepTime: "20 mins",
    isVeg: false,
  },
  {
    name: "Tofu Lentil Soup with Spinach",
    description: "Warming tofu and lentil soup",
    whyItHelps: "Tofu phytoestrogens and lentil fiber together support hormonal balance and gut health in PCOS",
    ingredients: ["150g tofu", "75g lentils", "100g spinach", "1 tbsp mustard oil", "garlic", "spices"],
    recipe: ["Simmer lentils with garlic and spices until soft.", "Pan-fry tofu cubes in mustard oil until golden on all sides.", "Stir spinach into the lentil soup and cook until wilted.", "Add the tofu, adjust seasoning, and serve."],
    mealType: "LUNCH",
    riskCategory: "LOW_RISK",
    calories: 350,
    carbs: 30,
    prepTime: "30 mins",
    isVeg: true,
  },

  // DINNER
  {
    name: "Rohu Fish Cauliflower Curry",
    description: "Classic Nepali fish curry with cauliflower",
    whyItHelps: "Omega-3 rich fish with low carb cauliflower. Proven to reduce PCOS inflammation markers",
    ingredients: ["200g rohu fish", "200g cauliflower", "1 tbsp mustard oil", "turmeric", "cumin", "salt"],
    recipe: ["Pan-fry the fish in mustard oil for 5 minutes each side, then remove from the pan.", "Stir-fry cauliflower with turmeric, cumin, and salt in the same pan.", "Return the fish, combine gently, and simmer for a further 5 minutes before serving hot."],
    mealType: "DINNER",
    riskCategory: "LOW_RISK",
    calories: 420,
    carbs: 18,
    prepTime: "25 mins",
    isVeg: false,
  },
  {
    name: "Mutton Zucchini Stir-fry",
    description: "Lean mutton with zucchini in Nepali spices",
    whyItHelps: "Zinc and iron from mutton support thyroid. Zucchini keeps carbs low for insulin management",
    ingredients: ["150g lean mutton", "200g zucchini", "1 tbsp mustard oil", "garlic", "spices"],
    recipe: ["Cook the mutton with garlic and spices until tender.", "Stir-fry the zucchini separately in a hot pan until lightly caramelised.", "Combine both, cook together for 5 minutes, finish with mustard oil, and serve."],
    mealType: "DINNER",
    riskCategory: "LOW_RISK",
    calories: 420,
    carbs: 14,
    prepTime: "35 mins",
    isVeg: false,
  },
  {
    name: "Rohu Fish Bitter Gourd Curry",
    description: "Traditional fish curry with blood sugar lowering bitter gourd",
    whyItHelps: "Bitter gourd charantin compound lowers blood glucose. Combined with omega-3 fish maximizes PCOS benefit",
    ingredients: ["200g rohu fish", "150g bitter gourd", "1 tbsp mustard oil", "turmeric", "salt"],
    recipe: ["Slice the bitter gourd, sprinkle with salt, and set aside for 10 minutes to reduce bitterness, then rinse.", "Pan-fry the fish in mustard oil until golden on both sides.", "In the same pan, cook the bitter gourd with turmeric until softened.", "Combine with the fish and serve."],
    mealType: "DINNER",
    riskCategory: "LOW_RISK",
    calories: 370,
    carbs: 14,
    prepTime: "30 mins",
    isVeg: false,
  },
  {
    name: "Chicken Eggplant Curry with Brown Rice",
    description: "Lean chicken and eggplant curry with a small portion of brown rice",
    whyItHelps: "Brown rice fiber slows glucose absorption. Eggplant antioxidants reduce PCOS oxidative stress",
    ingredients: ["150g chicken", "150g eggplant", "50g brown rice", "1 tbsp mustard oil", "spices"],
    recipe: ["Cook the brown rice according to packet instructions.", "Cook chicken in mustard oil with spices, then add diced eggplant and simmer until tender.", "Serve the curry over a small portion of brown rice."],
    mealType: "DINNER",
    riskCategory: "LOW_RISK",
    calories: 460,
    carbs: 42,
    prepTime: "40 mins",
    isVeg: false,
  },
  {
    name: "Tofu Palak Spinach Curry",
    description: "Creamy spinach curry with tofu",
    whyItHelps: "Tofu isoflavones reduce androgen levels. Palak iron combats PCOS-related anemia",
    ingredients: ["200g tofu", "200g palak spinach", "1 tbsp mustard oil", "garlic", "ginger", "spices"],
    recipe: ["Blend the spinach into a smooth purée.", "Cook the purée in mustard oil with garlic, ginger, and spices for 5 minutes.", "Add pan-fried tofu cubes, stir gently, and simmer for a further 10 minutes before serving."],
    mealType: "DINNER",
    riskCategory: "LOW_RISK",
    calories: 360,
    carbs: 16,
    prepTime: "25 mins",
    isVeg: true,
  },
  {
    name: "Mutton Green Beans Stir-fry",
    description: "Lean mutton with fresh green beans",
    whyItHelps: "Green beans chromium content improves insulin sensitivity. Mutton zinc supports reproductive health",
    ingredients: ["150g lean mutton", "200g green beans", "1 tbsp mustard oil", "garlic", "spices"],
    recipe: ["Cook the mutton with garlic and spices until tender.", "Blanch the green beans in boiling water for 2 minutes, then drain.", "Combine mutton and green beans in the pan, stir-fry together for 5 minutes, and serve hot."],
    mealType: "DINNER",
    riskCategory: "LOW_RISK",
    calories: 400,
    carbs: 16,
    prepTime: "35 mins",
    isVeg: false,
  },
  {
    name: "Rohu Fish Spinach Curry",
    description: "Simple fish and spinach curry",
    whyItHelps: "Weekly omega-3 from fish combined with spinach folate supports reproductive health in PCOS",
    ingredients: ["200g rohu fish", "200g spinach", "1 tbsp mustard oil", "garlic", "turmeric", "salt"],
    recipe: ["Fry the fish in mustard oil over medium heat until cooked through, then set aside.", "In the same pan, sauté garlic with turmeric, add spinach, and cook until wilted.", "Return the fish, cook together for 8 minutes, and serve hot."],
    mealType: "DINNER",
    riskCategory: "LOW_RISK",
    calories: 410,
    carbs: 10,
    prepTime: "20 mins",
    isVeg: false,
  },

  // SNACK
  {
    name: "Cucumber Lentil Dip",
    description: "Fresh cucumber with protein-rich lentil dip",
    whyItHelps: "Lentil dip adds plant protein to a hydrating snack. Keeps blood sugar stable between meals",
    ingredients: ["1 cucumber", "50g cooked lentils", "lemon", "salt", "cumin"],
    recipe: ["Blend the cooked lentils with lemon juice, cumin, and salt until smooth.", "Slice the cucumber into sticks and serve alongside the dip."],
    mealType: "SNACK",
    riskCategory: "LOW_RISK",
    calories: 120,
    carbs: 18,
    prepTime: "10 mins",
    isVeg: true,
  },
  {
    name: "Almonds",
    description: "Simple handful of raw almonds",
    whyItHelps: "Almonds magnesium and healthy fats reduce insulin resistance and androgen levels in PCOS",
    ingredients: ["20 almonds"],
    recipe: ["Serve as is."],
    mealType: "SNACK",
    riskCategory: "LOW_RISK",
    calories: 120,
    carbs: 5,
    prepTime: "1 min",
    isVeg: true,
  },
  {
    name: "Almond Butter with Celery",
    description: "Crunchy celery sticks with almond butter",
    whyItHelps: "Almond butter healthy fats with celery fiber. Perfect low carb snack for PCOS management",
    ingredients: ["3 stalks celery", "2 tbsp almond butter"],
    recipe: ["Wash the celery and cut into even sticks.", "Spread almond butter onto each stick and serve fresh."],
    mealType: "SNACK",
    riskCategory: "LOW_RISK",
    calories: 180,
    carbs: 8,
    prepTime: "5 mins",
    isVeg: true,
  },
  {
    name: "Yogurt with Chia Seeds",
    description: "Simple chia seed yogurt bowl",
    whyItHelps: "Chia fiber and yogurt probiotics together improve gut-hormone axis disrupted by PCOS",
    ingredients: ["150g yogurt", "5g chia seeds"],
    recipe: ["Stir chia seeds into the yogurt and allow to sit for 5 minutes before serving."],
    mealType: "SNACK",
    riskCategory: "LOW_RISK",
    calories: 160,
    carbs: 14,
    prepTime: "6 mins",
    isVeg: true,
  },
  {
    name: "Roasted Chickpeas with Pickle",
    description: "Crunchy chickpeas with fermented pickle",
    whyItHelps: "Chickpeas slow carb release prevents snack-time blood sugar spikes. Pickle probiotics support gut health",
    ingredients: ["20g chickpeas", "pickle vegetables", "1 tsp oil", "spices"],
    recipe: ["Toss the chickpeas with oil and spices and roast in a dry pan until crisp.", "Serve alongside the pickle."],
    mealType: "SNACK",
    riskCategory: "LOW_RISK",
    calories: 130,
    carbs: 16,
    prepTime: "12 mins",
    isVeg: true,
  },
  {
    name: "Local Berries with Almonds",
    description: "Fresh local berries with a handful of almonds",
    whyItHelps: "Berries anthocyanins reduce PCOS inflammation. Almonds healthy fats slow sugar absorption from berries",
    ingredients: ["75g local berries", "10 almonds"],
    recipe: ["Rinse the berries and serve with almonds."],
    mealType: "SNACK",
    riskCategory: "LOW_RISK",
    calories: 150,
    carbs: 16,
    prepTime: "3 mins",
    isVeg: true,
  },
  {
    name: "Cauliflower Chips",
    description: "Crispy baked cauliflower florets",
    whyItHelps: "Low carb alternative to chips. Cauliflower fiber supports gut health and reduces PCOS bloating",
    ingredients: ["200g cauliflower", "1 tsp oil", "salt", "turmeric", "cumin"],
    recipe: ["Cut the cauliflower into small, even florets.", "Toss with oil, salt, turmeric, and cumin until well coated.", "Spread on a baking tray and bake at 200°C for 20 minutes until crisp and golden.", "Serve immediately."],
    mealType: "SNACK",
    riskCategory: "LOW_RISK",
    calories: 100,
    carbs: 12,
    prepTime: "25 mins",
    isVeg: true,
  },

  
  //General Meals


  // BREAKFAST
  {
    name: "Yogurt with Berries and Almonds",
    description: "Classic PCOS-friendly breakfast bowl",
    whyItHelps: "Balanced protein, healthy fats and antioxidants. Standard Mediterranean diet breakfast proven to help PCOS",
    ingredients: ["150g yogurt", "50g berries", "10 almonds"],
    recipe: ["Combine yogurt and berries in a bowl, top with almonds, and serve fresh."],
    mealType: "BREAKFAST",
    riskCategory: "GENERAL",
    calories: 270,
    carbs: 26,
    prepTime: "5 mins",
    isVeg: true,
  },
  {
    name: "Egg Paneer Scramble",
    description: "Double protein scramble with eggs and paneer",
    whyItHelps: "High protein breakfast reduces hunger hormones disrupted by PCOS. Supports stable blood sugar all morning",
    ingredients: ["2 eggs", "100g paneer", "1 tsp oil", "salt", "pepper", "coriander"],
    recipe: ["Crumble the paneer into small pieces.", "Beat the eggs with salt and pepper.", "Heat oil in a pan and scramble the eggs and paneer together until just set.", "Garnish with fresh coriander and serve."],
    mealType: "BREAKFAST",
    riskCategory: "GENERAL",
    calories: 380,
    carbs: 6,
    prepTime: "10 mins",
    isVeg: true,
  },
  {
    name: "Grilled Paneer with Cucumber",
    description: "Simple grilled paneer with fresh cucumber",
    whyItHelps: "High protein low carb breakfast. Supports weight management which directly improves PCOS symptoms",
    ingredients: ["150g paneer", "1 cucumber", "1 tsp oil", "salt", "pepper"],
    recipe: ["Cut paneer into even slices and brush lightly with oil.", "Grill over medium-high heat for 3 minutes each side until golden.", "Slice the cucumber and serve alongside, seasoned with salt and pepper."],
    mealType: "BREAKFAST",
    riskCategory: "GENERAL",
    calories: 280,
    carbs: 8,
    prepTime: "12 mins",
    isVeg: true,
  },
  {
    name: "Berry Spinach Smoothie",
    description: "Antioxidant rich green smoothie",
    whyItHelps: "Anti-inflammatory berries and iron-rich spinach address two key PCOS concerns in one drink",
    ingredients: ["100g spinach", "75g berries", "150g yogurt", "5g chia seeds"],
    recipe: ["Blend the spinach and yogurt until completely smooth.", "Add the berries and blend again.", "Stir in the chia seeds and serve immediately."],
    mealType: "BREAKFAST",
    riskCategory: "GENERAL",
    calories: 240,
    carbs: 28,
    prepTime: "5 mins",
    isVeg: true,
  },
  {
    name: "Avocado Egg Boat",
    description: "Egg baked in avocado with spices",
    whyItHelps: "Monounsaturated fats from avocado improve insulin sensitivity. High satiety prevents overeating in PCOS",
    ingredients: ["1 avocado", "2 eggs", "salt", "cumin", "chili flakes"],
    recipe: ["Halve and pit the avocado, scooping out extra flesh to make room for the egg.", "Crack an egg into each half and season with salt, cumin, and chili flakes.", "Bake at 200°C for 15 minutes until the whites are set.", "Serve immediately."],
    mealType: "BREAKFAST",
    riskCategory: "GENERAL",
    calories: 360,
    carbs: 12,
    prepTime: "20 mins",
    isVeg: true,
  },
  {
    name: "Almonds Paneer Onion Plate",
    description: "Protein and fat rich breakfast plate",
    whyItHelps: "Combined protein from paneer and healthy fats from almonds provide sustained energy without carb crash",
    ingredients: ["150g paneer", "1 onion", "10 almonds", "1 tsp oil", "salt"],
    recipe: ["Sauté the sliced onion in oil until golden.", "Add cubed paneer to the pan and cook until lightly browned.", "Transfer to a plate and serve with almonds on the side."],
    mealType: "BREAKFAST",
    riskCategory: "GENERAL",
    calories: 340,
    carbs: 14,
    prepTime: "15 mins",
    isVeg: true,
  },
  {
    name: "Spinach Egg Scramble",
    description: "Classic spinach and egg scramble",
    whyItHelps: "Iron, protein and B vitamins in one simple breakfast. Addresses nutritional deficiencies common in PCOS",
    ingredients: ["2 eggs", "150g spinach", "1 tsp oil", "garlic", "salt"],
    recipe: ["Heat oil in a pan and sauté garlic until fragrant.", "Add the spinach and cook until wilted.", "Beat the eggs with salt, pour into the pan, and scramble gently until just set.", "Serve immediately."],
    mealType: "BREAKFAST",
    riskCategory: "GENERAL",
    calories: 260,
    carbs: 6,
    prepTime: "10 mins",
    isVeg: true,
  },

  // LUNCH
  {
    name: "Tuna Pickle Spinach with Mung Beans",
    description: "Filling tuna salad with fermented pickle and lentils",
    whyItHelps: "Complete meal with protein, fiber and probiotics. Addresses insulin resistance and gut health together",
    ingredients: ["150g tuna", "pickle vegetables", "100g spinach", "75g mung beans", "mustard oil"],
    recipe: ["Cook the mung beans until tender, then drain.", "Drain and flake the tuna.", "Combine tuna, mung beans, spinach, and pickled vegetables in a bowl.", "Drizzle with mustard oil, toss well, and serve."],
    mealType: "LUNCH",
    riskCategory: "GENERAL",
    calories: 380,
    carbs: 32,
    prepTime: "20 mins",
    isVeg: false,
  },
  {
    name: "Chicken Spinach Choila",
    description: "Nepali style spiced chicken with spinach",
    whyItHelps: "Traditional Nepali preparation with lean protein. Mustard oil anti-inflammatory properties reduce PCOS symptoms",
    ingredients: ["200g chicken", "100g spinach", "1 tbsp mustard oil", "garlic", "ginger", "spices"],
    recipe: ["Boil the chicken with ginger and garlic until cooked through, then shred.", "Toss with spices and set aside.", "Sauté the spinach until wilted, then combine with the chicken and mustard oil.", "Serve warm."],
    mealType: "LUNCH",
    riskCategory: "GENERAL",
    calories: 360,
    carbs: 8,
    prepTime: "30 mins",
    isVeg: false,
  },
  {
    name: "Red Lentil Spinach Salad",
    description: "Warm lentil salad with fresh spinach",
    whyItHelps: "Lentil plant protein and folate support reproductive health. Spinach iron reduces PCOS fatigue",
    ingredients: ["100g red lentils", "150g spinach", "1 tbsp mustard oil", "lemon", "cumin", "salt"],
    recipe: ["Cook the lentils until just tender, then drain.", "While still warm, toss with fresh spinach so it wilts slightly.", "Dress with mustard oil and lemon juice, season with cumin and salt, and serve."],
    mealType: "LUNCH",
    riskCategory: "GENERAL",
    calories: 300,
    carbs: 36,
    prepTime: "25 mins",
    isVeg: true,
  },
  {
    name: "Egg Onion Salad",
    description: "Simple boiled egg and onion salad",
    whyItHelps: "Onion quercetin reduces PCOS inflammation. Eggs complete amino acid profile supports hormone production",
    ingredients: ["3 eggs", "1 onion", "1 tbsp mustard oil", "coriander", "salt", "lemon"],
    recipe: ["Boil and slice the eggs.", "Thinly slice the onion and combine with the eggs.", "Dress with mustard oil and lemon, season with salt, and garnish with fresh coriander."],
    mealType: "LUNCH",
    riskCategory: "GENERAL",
    calories: 270,
    carbs: 12,
    prepTime: "15 mins",
    isVeg: true,
  },
  {
    name: "Chickpea Lentil Paneer Bowl",
    description: "Triple protein bowl with chickpeas, lentils and paneer",
    whyItHelps: "Plant and dairy proteins together. Chickpea inositol directly improves insulin signaling in PCOS",
    ingredients: ["50g chickpeas", "50g lentils", "100g paneer", "1 tbsp mustard oil", "spices"],
    recipe: ["Cook chickpeas and lentils until tender, then drain.", "Pan-fry paneer cubes until golden.", "Combine everything with spices and drizzle with mustard oil before serving."],
    mealType: "LUNCH",
    riskCategory: "GENERAL",
    calories: 420,
    carbs: 38,
    prepTime: "30 mins",
    isVeg: true,
  },
  {
    name: "Rohu Fish Lettuce Wrap",
    description: "Fresh fish in crispy lettuce wrap",
    whyItHelps: "Omega-3 rich fish in a zero-carb wrap. Maximum PCOS anti-inflammatory benefit with minimal carbs",
    ingredients: ["200g rohu fish", "4 lettuce leaves", "cucumber", "mint", "mustard oil", "lemon"],
    recipe: ["Pan-fry the fish in mustard oil until flaky and cooked through.", "Break into pieces and season.", "Place into lettuce leaves with cucumber and fresh mint, squeeze lemon over the top, and serve."],
    mealType: "LUNCH",
    riskCategory: "GENERAL",
    calories: 320,
    carbs: 6,
    prepTime: "20 mins",
    isVeg: false,
  },
  {
    name: "Lentil Soup with Tofu and Spinach",
    description: "Hearty warming soup with plant proteins",
    whyItHelps: "Triple plant-based nutrition. Lentil, tofu and spinach combination addresses PCOS nutritional deficiencies",
    ingredients: ["75g lentils", "150g tofu", "100g spinach", "1 tbsp mustard oil", "garlic", "spices"],
    recipe: ["Simmer lentils with garlic and spices until soft.", "Pan-fry tofu cubes in mustard oil until golden.", "Stir spinach into the soup and cook until wilted.", "Add tofu, adjust seasoning, and serve."],
    mealType: "LUNCH",
    riskCategory: "GENERAL",
    calories: 340,
    carbs: 28,
    prepTime: "30 mins",
    isVeg: true,
  },

  // DINNER
  {
    name: "Rohu Fish Cauliflower Curry",
    description: "Classic Nepali fish curry",
    whyItHelps: "Standard Mediterranean-inspired PCOS dinner. Omega-3 and fiber combination reduces insulin resistance",
    ingredients: ["200g rohu fish", "200g cauliflower", "1 tbsp mustard oil", "spices"],
    recipe: ["Fry the fish in mustard oil for 5 minutes each side, then set aside.", "In the same pan, stir-fry the cauliflower with spices until tender.", "Return the fish, combine gently, and serve hot."],
    mealType: "DINNER",
    riskCategory: "GENERAL",
    calories: 430,
    carbs: 16,
    prepTime: "25 mins",
    isVeg: false,
  },
  {
    name: "Mutton Stir-fry with Chilies",
    description: "Spicy lean mutton stir-fry",
    whyItHelps: "Capsaicin in chilies boosts metabolism. Lean mutton provides zinc essential for PCOS hormone regulation",
    ingredients: ["150g lean mutton", "green chilies", "onion", "1 tbsp mustard oil", "garlic", "spices"],
    recipe: ["Marinate the mutton with garlic and spices for 10 minutes.", "Stir-fry with sliced onion in mustard oil over high heat.", "Add the green chilies and cook for a further 3 minutes.", "Serve hot."],
    mealType: "DINNER",
    riskCategory: "GENERAL",
    calories: 400,
    carbs: 10,
    prepTime: "30 mins",
    isVeg: false,
  },
  {
    name: "Rohu Fish with Buckwheat",
    description: "Fish with a small portion of buckwheat",
    whyItHelps: "Buckwheat D-chiro-inositol directly improves insulin signaling in PCOS. Fish omega-3 reduces inflammation",
    ingredients: ["200g rohu fish", "50g buckwheat", "1 tbsp mustard oil", "spices"],
    recipe: ["Cook the buckwheat according to packet instructions.", "Pan-fry the fish in mustard oil with spices until cooked through.", "Serve the fish over the buckwheat."],
    mealType: "DINNER",
    riskCategory: "GENERAL",
    calories: 440,
    carbs: 28,
    prepTime: "25 mins",
    isVeg: false,
  },
  {
    name: "Chicken Eggplant with Quinoa",
    description: "Lean chicken and eggplant curry with quinoa",
    whyItHelps: "Quinoa complete protein supports muscle. Eggplant nasunin antioxidant protects cells damaged by PCOS oxidative stress",
    ingredients: ["150g chicken", "150g eggplant", "50g quinoa", "1 tbsp mustard oil", "spices"],
    recipe: ["Cook the quinoa according to packet instructions.", "Prepare the curry by cooking chicken in mustard oil with spices, then adding diced eggplant until tender.", "Serve the curry over the quinoa."],
    mealType: "DINNER",
    riskCategory: "GENERAL",
    calories: 460,
    carbs: 36,
    prepTime: "35 mins",
    isVeg: false,
  },
  {
    name: "Tofu Bitter Gourd Spinach Curry",
    description: "Triple benefit curry for PCOS",
    whyItHelps: "Bitter gourd lowers glucose, tofu balances hormones, spinach provides iron. Three PCOS benefits in one dish",
    ingredients: ["200g tofu", "150g bitter gourd", "150g spinach", "1 tbsp mustard oil", "spices"],
    recipe: ["Slice the bitter gourd, salt it, and leave for 10 minutes to reduce bitterness, then rinse.", "Pan-fry tofu cubes until golden and set aside.", "Cook the bitter gourd in mustard oil with spices until softened.", "Add spinach and tofu, cook for a further 3 minutes, and serve."],
    mealType: "DINNER",
    riskCategory: "GENERAL",
    calories: 370,
    carbs: 16,
    prepTime: "30 mins",
    isVeg: true,
  },
  {
    name: "Mutton Green Beans",
    description: "Lean mutton with fresh green beans",
    whyItHelps: "Green beans silicon supports bone health affected by PCOS. Mutton complete protein maintains healthy weight",
    ingredients: ["150g lean mutton", "200g green beans", "1 tbsp mustard oil", "garlic", "spices"],
    recipe: ["Cook the mutton with garlic and spices until tender.", "Blanch the green beans in boiling water for 2 minutes, then drain.", "Combine both in the pan and stir-fry together briefly.", "Finish with mustard oil and serve."],
    mealType: "DINNER",
    riskCategory: "GENERAL",
    calories: 390,
    carbs: 14,
    prepTime: "35 mins",
    isVeg: false,
  },
  {
    name: "Rohu Fish Salad",
    description: "Light fish salad with fresh vegetables",
    whyItHelps: "Light dinner prevents evening blood sugar spike. Omega-3 from fish works overnight to reduce PCOS inflammation",
    ingredients: ["200g rohu fish", "mixed vegetables", "1 tbsp mustard oil", "lemon", "salt"],
    recipe: ["Grill the fish until cooked through and flaky, then break into chunks.", "Toss with mixed vegetables and mustard oil.", "Squeeze lemon over the top, season with salt, and serve."],
    mealType: "DINNER",
    riskCategory: "GENERAL",
    calories: 360,
    carbs: 10,
    prepTime: "20 mins",
    isVeg: false,
  },

  // SNACK
  {
    name: "Cucumber Lentil Dip",
    description: "Refreshing cucumber with protein lentil dip",
    whyItHelps: "Lentil dip protein and cucumber fiber combined prevent blood sugar dips between meals",
    ingredients: ["1 cucumber", "50g lentils", "lemon", "cumin", "salt"],
    recipe: ["Cook the lentils until soft, then blend with lemon juice, cumin, and salt until smooth.", "Slice the cucumber into sticks and serve with the dip."],
    mealType: "SNACK",
    riskCategory: "GENERAL",
    calories: 120,
    carbs: 18,
    prepTime: "10 mins",
    isVeg: true,
  },
  {
    name: "Almonds",
    description: "Handful of raw almonds",
    whyItHelps: "Daily almond consumption shown to reduce fasting insulin by 8% in PCOS women",
    ingredients: ["15 almonds"],
    recipe: ["Serve as is."],
    mealType: "SNACK",
    riskCategory: "GENERAL",
    calories: 100,
    carbs: 4,
    prepTime: "1 min",
    isVeg: true,
  },
  {
    name: "Celery with Almond Butter",
    description: "Crunchy celery with creamy almond butter",
    whyItHelps: "Zero sugar snack with healthy fats. Keeps afternoon insulin levels stable in PCOS management",
    ingredients: ["3 stalks celery", "2 tbsp almond butter"],
    recipe: ["Cut the celery into even sticks.", "Spread almond butter onto each stick and serve fresh."],
    mealType: "SNACK",
    riskCategory: "GENERAL",
    calories: 180,
    carbs: 8,
    prepTime: "5 mins",
    isVeg: true,
  },
  {
    name: "Yogurt with Chia Seeds",
    description: "Simple chia yogurt",
    whyItHelps: "Probiotic and prebiotic combination. Gut microbiome health is directly linked to PCOS hormone balance",
    ingredients: ["150g yogurt", "5g chia seeds"],
    recipe: ["Stir chia seeds into the yogurt and allow to sit for 5 minutes before serving."],
    mealType: "SNACK",
    riskCategory: "GENERAL",
    calories: 160,
    carbs: 14,
    prepTime: "6 mins",
    isVeg: true,
  },
  {
    name: "Roasted Chickpeas with Pickle",
    description: "Crunchy chickpeas with fermented pickle",
    whyItHelps: "Inositol in chickpeas improves egg quality in PCOS. Pickle fermentation supports gut health",
    ingredients: ["20g chickpeas", "pickle", "1 tsp oil", "spices"],
    recipe: ["Toss chickpeas with oil and spices and roast in a dry pan for 10 minutes until crisp.", "Serve with pickle on the side."],
    mealType: "SNACK",
    riskCategory: "GENERAL",
    calories: 130,
    carbs: 16,
    prepTime: "12 mins",
    isVeg: true,
  },
  {
    name: "Berries with Almonds",
    description: "Fresh berries with almonds",
    whyItHelps: "Antioxidant rich berries reduce oxidative stress. Almonds healthy fats prevent sugar absorption spike from berries",
    ingredients: ["75g berries", "10 almonds"],
    recipe: ["Rinse the berries and serve with almonds."],
    mealType: "SNACK",
    riskCategory: "GENERAL",
    calories: 150,
    carbs: 16,
    prepTime: "3 mins",
    isVeg: true,
  },
  {
    name: "Cauliflower Fritters",
    description: "Crispy baked cauliflower fritters",
    whyItHelps: "Low carb snack that satisfies cravings. Cauliflower sulforaphane detoxifies excess estrogen in PCOS",
    ingredients: ["200g cauliflower", "1 egg", "spices", "1 tsp oil"],
    recipe: ["Grate the cauliflower and squeeze out any excess moisture.", "Mix with beaten egg and spices until combined.", "Form into small patties and pan-fry in oil over medium heat until golden on both sides.", "Serve immediately."],
    mealType: "SNACK",
    riskCategory: "GENERAL",
    calories: 140,
    carbs: 10,
    prepTime: "20 mins",
    isVeg: true,
  },
]; async function main() {
  console.log("Seeding meals...");
  await prisma.meal.deleteMany();
  await prisma.meal.createMany({ data: meals });
  console.log("Meals seeded:", meals.length, "total");
  console.log("HIGH_RISK:", meals.filter((m) => m.riskCategory === "HIGH_RISK").length);
  console.log("LOW_RISK:", meals.filter((m) => m.riskCategory === "LOW_RISK").length);
  console.log("GENERAL:", meals.filter((m) => m.riskCategory === "GENERAL").length);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });